variable "redis_master_image" {
  description = "Docker Image for redis Master"
  default = "gcr.io/google_containers/redis:e2e"
}

variable "redis_slave_image" {
  description = "Docker image for redis slave"
  default = "gcr.io/google_samples/gb-redisslave:v1"
}

variable "redis_slave_replicas" {
  description = "Number of replicas for redis slave"
  default = 2
}

variable "frontend_replicas" {
  description = "Number of replicas for frontend container"
  default = 3
}

variable "frontend_node_port" {
  description = "Node Port for Frontend service"
  default = 31080
}

variable "frontend_image" {
  description = "Frontend image for guestbook application"
  default = "gcr.io/google_samples/gb-frontend:v3"
}

variable "follows" {
  description = "Run this module after"
  default = ""
}

variable "kube_config_file" {
  description = "config file generated by kubeadm"
  default = ""
}